config/routes.rb
Friday::Application.routes.draw do
  root to: 'sessions#new'
  resources :users do
      resources :posts
  end
  
  resources :posts do
    resources :comments
    resources :likes
  end
  resources :friendships
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  validates :post_id, :presence => true
  attr_accessible :body, :user_id, :post_id
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id
  belongs_to :user
  belongs_to :friend, :class_name => 'User' 
  
  validates  :user_id, :uniqueness => {:scope => :friend_id}
end

app/models/like.rb
class Like < ActiveRecord::Base
  
  attr_accessible :user_id, :post_id
  belongs_to :usergm
  belongs_to :post
  validates :user_id , :uniqueness => {:scope => :post_id}

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :title
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy

  validates :content, presence: true

  def get_recent_two_likers(current_user)
  	user_ids = self.likes(:include => :user).collect(&:user_id).delete_if { |x| x == current_user.id }.last(2)
  	User.find(user_ids).map(&:username)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :friendships  
  has_many :friends, :through => :friendships  

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  attr_accessible :dob, :email, :fullname, :gender, :password, :username, :password_confirmation, :pic
  
  has_secure_password
  has_attached_file :pic, :styles => 
     { :medium => "300x300>", :thumb => "100x100>" }

  before_create :create_remember_token

  validates :username, presence: true, length: { maximum: 15 },
            uniqueness: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :dob,
  :date => {:before => Date.today, :message => 'must be before today'}   
  def already_likes?(post)
      self.likes.find(:all, :conditions => ['post_id = ?', post.id]).size > 0
  end
  private
  def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
  end 
  
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  before_filter :login_required
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def create
    @post = Post.find(params[:post_id])
    opts = params[:comment].merge(:user_id => current_user.id)
    @comment = @post.comments.create(opts)
    redirect_to :back 
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to :back
    flash[:notice] = "Comment deleted"
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	
  def create  
  		@friendship = current_user.friendships.build(:friend_id => params[:friend_id])  
  		if @friendship.save  
    		flash[:notice] = "Added friend"  
    		redirect_to users_path  
  		else  
    		flash[:notice] = "Unable to add friend"  
    	  redirect_to users_path  
  		end  
	end  
	
  def destroy  
  		@friendship = current_user.friendships.find(params[:id])  
        @friendship.destroy 
  		  flash[:notice] = "Removed friendship"  
        redirect_to current_user  
	end  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_filter :load_post
  before_filter :load_object, :only => [:destroy]

  def create
    opts = {:user_id => current_user.id, :post_id => params[:post_id]}
    @like = @post.likes.create(opts)

    respond_to do |format|
      if @like.save    
        format.html { redirect_to :back }    
      else
        format.html { redirect_to :back }
      end
    end
  end

  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to :back }
    end
  end

  protected

  def load_post
    @post = Post.find(params[:post_id])
  end
  
  def load_object
    @like = (@post || load_post).likes.find(params[:id])
  end
end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def HOme
  end

  def Signin
  end

  def Signup
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def show
    @post = Post.find(params[:id])
    respond_to do |format|
    format.html
    end
  end
	
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(params[:post])
    respond_to do |format|
	    if @post.save    
      	format.html { redirect_to @user, notice: 'Post was successfully created.' }
    	else
    		format.html { redirect_to @user }
        flash[:error] = 'Post must have Content !! '
 	 		end
		end
	end
    
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end
    
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to :back
    flash[:notice] = "Post destroyed"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :login_required
 
  def new
  end
 
  def create
  	user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
    	sign_in user
    	redirect_to user_path(user)
      
    else 
      render 'new'
      flash[:error] = 'Invalid email/password combination'
    end
  end
  
  def destroy
    sign_out
    flash[:notice] = 'You have been logged out'
    redirect_to root_url
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :login_required, :only => [:new, :create] #:except => [:index]
  
  def index
    @users = User.find(:all, :conditions => ["id != ?", current_user.id])
    respond_to do |format|
      format.html 
    end
  end

  def show
    @user = User.find(params[:id])
    render "show"
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Profile updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def create
    @user = User.new(params[:user])
      if @user.save
        flash[:success] = "Welcome!"
        UserMailer.welcome_email(@user).deliver
        redirect_to signin_path
      else
        render  'new'  
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
	    cookies.permanent[:remember_token] = user.remember_token
    	self.current_user = user
  end

  def current_user=(user)
    	@current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def login_required
    redirect_to signin_path, :notice => 'Login required!' unless signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/comments/_comment.html.erb
<p>
 <b><%= comment.user.username %> : </b> 
 <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_for([post, post.comments.build]) do |f| %>
	<div>
		<%= f.label :Body %><br />
		<%= f.text_area :body, :rows => 10, :cols => 30%>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/friendships/index.html.erb
Friends

<ul>  
    <% for friendship in @user.friendships %>  
  	 <li>  
    	<%= friendship.friend.username %>
      
    	 <%= link_to "Remove", friendship, :confirm => 'Are you sure you want to remove?', :method => :delete %>
     
  	 </li>
<<<<<<< HEAD
=======
   <br>
>>>>>>> 8212443... no comments
   
  </ul>  
  <% end %>

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
<div>
      <%= f.submit  "Like"%>
 </div>
 <% end %>

app/views/posts/_form.html.erb
<%= form_for([@user, @user.posts.build]) do |f| %>
  <div>
    <%= f.label :Title %><br />
    <%= f.text_field :title%>
  </div>
  <div>
    <%= f.label :Content %><br />
    <%= f.text_area :content , :rows => 10, :cols => 30%>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
    <b>Title:</b> 
    <%= post.title %> <br />

    <% if current_user.already_likes?(post) %>
        <%- like = post.likes.where(:user_id => current_user.id).first %>
        <%= link_to "Unlike", post_like_path(post, like), :method => :delete %> 
       <% if post.likes.count > 2 %> 
           You, <%= post.get_recent_two_likers(current_user).join(', ') %> and  <%= post.likes.count-3 %> others like this
       <% else %>
            You and <%= post.get_recent_two_likers(current_user).join(', ') %> like this
        <% end %>
    <% else %>
        <%= link_to "Like", post_likes_path(:post_id => post), :method => :post %>
        <% if post.likes.count > 2 %>
             <%= post.get_recent_two_likers(current_user).join(', ') %> and  <%= post.likes.count-2 %> others like this
        <% else %>
            <%= post.get_recent_two_likers(current_user).join(' and ') %> like this
        <% end %>
    <% end %>  

    <% if @user == current_user %>
        <%= link_to "Delete", post_path(post), :confirm => "Are you sure want to delete?", :method => :delete %> <br />
    <% end %> <br />
</p>
<p>
    <b> Posted By : </b>
    <%= post.user.username %>
</p>
<p>
    <b> Content: </b>
    <%= post.content %>
</p>
<p>
    <b> Number of comments: </b>
    <%= post.comments.count %>
</p>
<p>
    <b> Comments: </b>
    <%= render post.comments %>
</p>
<% if @user == current_user || current_user.friends.include?(@user) %>
    <h2>Add a comment:</h2>
    <%= render "comments/form", :post => post %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= render 'form' %>

app/views/posts/index.html.erb
<table>
  <thead>
    <tr>
      <td>Title</td>
      <td>Content</td>
    </tr>
  </thead>
  <tbody>
    <%= render @current_user.posts %>
  </tbody>
</table>
<div>
  <%= link_to "Back", @user_path %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p>
    <h1>
    <%= post.title %>
    <%= render "likes/form", :post => post %>
    </h1>
  </p>
 
  <p>
    <b>Content:</b>
    <%= post.content %>
  </p>
<p>
  <b>Comments :</b>
  <%= render post.comments %>
</p>
<h2>Add a comment:</h2>

<%= render "comments/form", :post => post %>
<h3> <%= link_to "Back", user_path %> <br/>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :Username %><br />
    <%= f.text_field :username %>
  </div>
  
  <div>
    <%= f.label :Fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  
  <div>
     <%= f.label :Gender %><br />
    <%= radio_button_tag(:gender, "Male") %>
    <%= label_tag(:male, "Male") %>
    <%= radio_button_tag(:gender, "Female") %>
    <%= label_tag(:female, "Female") %>
  </div>

  <div >
    <%= f.label :DoB %><br />
     <%= f.datepicker 'dob' %>
  </div> 

  <div>
    <%= f.label :Email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div>
    <%= f.label :Password %><br />
    <%= f.password_field :password %>
  </div>
  <%= f.label :password_confirmation, "Confirmation" %> <br/>
      <%= f.password_field :password_confirmation %>
  <div>
  
    <%= f.submit "Create my Account" %>

    <%= link_to "Back" , root_path %>
   </div>
<% end %>

app/views/users/_form1.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.label :Username %><br />
    <%= f.text_field :username, :placeholder => "User Name"%>
  </div>
  
  <div>
    <%= f.label :Email %><br />
    <%= f.text_field :email, :placeholder => "Email Id" %>
  </div>
  
  <div >
    <%= f.label :DoB %><br />
     <%= f.datepicker 'dob', :dateFormat => "dd/mm/yy"  %>
  </div>
  
  <div>
    <%= f.label :Password %><br />
    <%= f.password_field :password, :placeholder => "Minimum 6 Characters" %>
  </div>
  
  <div>
    <%= f.label :password_confirmation, "Confirmation" %> <br/>
    <%= f.password_field :password_confirmation, :placeholder => "Re-type Password" %>
  </div>
  
  <div>
    <%= f.submit "Create my Account" %> <br/>
    <%= link_to "Back" , root_path %>
  </div>

<% end %>

app/views/users/_form2.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :Username %><br />
    <%= f.text_field :username, :placeholder => "User Name"%>
  </div>

  <div>
    <%= f.label :Fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  
  <div>
     <b> Upload Profile Picture </b><br/>
     <%= f.file_field :pic %>
 </div>
  
  <div>
    <%= f.label :Email %><br />
    <%= f.text_field :email, :placeholder => "Email Id" %>
  </div>
  
  <div>
     <%= f.label :Gender %><br />
    <%= radio_button_tag(:gender, "Male") %>
    <%= label_tag(:male, "Male") %>
    <%= radio_button_tag(:gender, "Female") %>
    <%= label_tag(:female, "Female") %>
  </div>

  <div>
    <%= f.label :DoB %><br />
     <%= f.datepicker 'dob', :dateFormat => "dd/mm/yy"  %>
  </div> 
  
  <div>
    <%= f.label :Password %><br />
    <%= f.password_field :password, :placeholder => "Minimum 6 Characters" %>
  </div>
  
  <div>
    <%= f.label :password_confirmation, "Confirmation" %> <br/>
    <%= f.password_field :password_confirmation, :placeholder => "Re-type Password" %>
  </div>
  
  <div>
    <%= f.submit "Save" %> <br/>
  </div>
  
  <%= link_to 'Back', user_path %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form2' %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>Username</th>
    <th>Email</th> 
    <th>Posts</th>
    <th> </th>
    <th> </th>
  </tr>
  <% @users.each do |user| %>

    <tr>

      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.posts.count %></td>
      <td><%= link_to 'Show', user %></td>
      <td>
          <% unless current_user.friends.include?(user) %> 
            <%= link_to 'Add as Friend', friendships_path(:friend_id => user), :method => :post %>   
          <% end %>
      </td>  
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form1' %>

app/views/users/show.html.erb
<div style= "float :left;">
	<%= image_tag @user.pic.url(:thumb) %> 
</div>
<h2> <%= @user.username %> </h2> 
Number of posts: <%= @user.posts.count %><br/>
Number of comments: <%= @user.comments.count %></br/>
Number of likes: <%= @user.likes.count %><br/> <br />
<div style = "float :right;" />
  <h3>Friends</h3>  
  <ul style = "list-style-type: none;" >  
    <% for friendship in @user.friendships %>  
  	 <li >  
      <%= image_tag friendship.friend.pic.url(:thumb) %>
    	<%= friendship.friend.username %>
      <% if @user == current_user  %>
      	 <%= link_to "Remove", friendship, :confirm => 'Are you sure you want to remove?', :method => :delete %>
      <% end %>
     
  	 </li>
  <% end %>  
  </ul>  
</div>
<h2>Posts</h2> 
<%= render @user.posts %>
<% if @user == current_user %>
<h2>Add a post:</h2>
<%= render "posts/form" %>

<% end %>